### ISSUE TITLE
keyerror issue

### ISSUE THREAD

**Issue by mkinnaman** [rhshah/iAnnotateSV#28]
Hi I am interested in using your code here but running into an issue getting it to run:

`python iAnnotateSV.py -i iAnnotateSV/data/test/testData.txt -ofp test -o iAnnotateSV/data/test/ -r hg19 -d 3000 -v
Traceback (most recent call last):
  File "iAnnotateSV.py", line 350, in <module>
    main()
  File "iAnnotateSV.py", line 218, in main
    NewRefDF = hp.ExtendPromoterRegion(refDF, args.distance)
  File "/home/kinnamam/iAnnotateSV/iAnnotateSV/helper.py", line 42, in ExtendPromoterRegion
    df['geneStart'] = df['txStart']
  File "/home/kinnamam/.local/lib/python2.7/site-packages/pandas/core/frame.py", line 2927, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/kinnamam/.local/lib/python2.7/site-packages/pandas/core/indexes/base.py", line 2659, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'txStart'`

Any ideas how to troubleshoot this? Have tried running with my own data and example data, same result.

**Comment by rhshah** [comment]
Hello @mkinnaman, Thank you for taking the time to report the issue. Are the files in the `/iAnnotateSV/iAnnotateSV/data` folder correctly cloned? You need to use [git-lfs](https://git-lfs.github.com/) to clone this repository.

**Comment by mkinnaman** [comment]
Thanks - I didnt have git-ifs so recloned now and should be cloned correctly - Now getting a different error when I run:

`python iAnnotateSV.py -i /Users/kinnamam/Computational/iAnnotateSV/iAnnotateSV/data/test/testData.txt -ofp test -o /Users/kinnamam/Computational/iAnnotateSV/iAnnotateSV/data/test/ -r hg19 -d 3000
Traceback (most recent call last):
  File "iAnnotateSV.py", line 350, in <module>
    main()
  File "iAnnotateSV.py", line 220, in main
    annDF = processSV(svDF, NewRefDF, args)
  File "iAnnotateSV.py", line 276, in processSV
    intronframe1) = aeb.AnnotateEachBreakpoint(chr1, pos1, str1, refDF, args.autoSelect)
  File "/Users/kinnamam/Computational/iAnnotateSV/iAnnotateSV/AnnotateEachBreakpoint.py", line 150, in AnnotateEachBreakpoint
    (geneName,transcript,desc,zone,strandDirection,intronnum,intronframe) = ft.FindATranscript(coordData, df)
  File "/Users/kinnamam/Computational/iAnnotateSV/iAnnotateSV/FindTranscript.py", line 18, in FindATranscript
    idxMin = int(queryDF['d'].idxmin(axis=1))
  File "/Users/kinnamam/miniconda3/envs/iannotatesv/lib/python2.7/site-packages/pandas/core/series.py", line 1881, in idxmin
    i = nanops.nanargmin(com.values_from_object(self), skipna=skipna)
  File "/Users/kinnamam/miniconda3/envs/iannotatesv/lib/python2.7/site-packages/pandas/core/nanops.py", line 73, in _f
    raise TypeError(msg.format(name=f.__name__.replace('nan', '')))
TypeError: reduction operation 'argmin' not allowed for this dtype`

Thoughts?

**Comment by rhshah** [comment]
Hi, My apologies for late reply it seems when I updated to a newer version of pandas for, I did not test the auto-selection part. Please use the latest version

**Comment by mkinnaman** [comment]
Thank you! smooth sailing now - great tool

**Comment by rhshah** [comment]
I am glad it helps.
